// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorDgLLUtYR_vnUtSfrmw6YA19y6rZKlo',
    appId: '1:317386963003:web:996ab79e02a667f06d441e',
    messagingSenderId: '317386963003',
    projectId: 'mydairy-6ffdb',
    authDomain: 'mydairy-6ffdb.firebaseapp.com',
    databaseURL: 'https://mydairy-6ffdb-default-rtdb.firebaseio.com',
    storageBucket: 'mydairy-6ffdb.appspot.com',
    measurementId: 'G-SW3QP30BJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwulxncLoqIpkW4wQmSaA0iS-CIwhWeSw',
    appId: '1:317386963003:android:63804c7afb80d1a36d441e',
    messagingSenderId: '317386963003',
    projectId: 'mydairy-6ffdb',
    databaseURL: 'https://mydairy-6ffdb-default-rtdb.firebaseio.com',
    storageBucket: 'mydairy-6ffdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCS0BLvivQYRIAsFzN08Dfo_arnd72v38',
    appId: '1:317386963003:ios:01b5381569559f396d441e',
    messagingSenderId: '317386963003',
    projectId: 'mydairy-6ffdb',
    databaseURL: 'https://mydairy-6ffdb-default-rtdb.firebaseio.com',
    storageBucket: 'mydairy-6ffdb.appspot.com',
    iosBundleId: 'com.example.mydairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCS0BLvivQYRIAsFzN08Dfo_arnd72v38',
    appId: '1:317386963003:ios:01b5381569559f396d441e',
    messagingSenderId: '317386963003',
    projectId: 'mydairy-6ffdb',
    databaseURL: 'https://mydairy-6ffdb-default-rtdb.firebaseio.com',
    storageBucket: 'mydairy-6ffdb.appspot.com',
    iosBundleId: 'com.example.mydairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorDgLLUtYR_vnUtSfrmw6YA19y6rZKlo',
    appId: '1:317386963003:web:7cc604737c7b0f9f6d441e',
    messagingSenderId: '317386963003',
    projectId: 'mydairy-6ffdb',
    authDomain: 'mydairy-6ffdb.firebaseapp.com',
    databaseURL: 'https://mydairy-6ffdb-default-rtdb.firebaseio.com',
    storageBucket: 'mydairy-6ffdb.appspot.com',
    measurementId: 'G-VHPF2NZBFH',
  );
}
